### ISSUE TITLE
Polyfill for AR?

### ISSUE THREAD

**Issue by pampas93** [immersive-web/webxr-polyfill#73]
I'm trying to create an AR test from the latest chrome stable (76.0.3809.111) browser on my pixel 2, but after enabling all the WebXR flags, I get an exception while calling the `navigator.xr.requestDevice()` with `TypeError: navigator.xr.requestDevice is not a function` 

I get the above error with and without using the webxr-polyfill.js within my loading page. Any idea if or how and get around this? Or is it just implemented for supporting VR for now?

The above works fine on the Chrome Dev (71.0.3574.0).
